export enum ProblemSubmissionStatusEnum {
    JUDGE_QUEUE = "JUDGE_QUEUE",
    CORRECT_ANSWER = "CORRECT_ANSWER",
    WRONG_ANSWER = "WRONG_ANSWER",
    WRONG_COMPLEXITY = "WRONG_COMPLEXITY",
    RUNTIME_ERROR = "RUNTIME_ERROR",
    COMPILE_ERROR = "COMPILE_ERROR",
}